
export const mainCategories = [
    { title: "Bottles and Flasks", slug: "bottles-and-flasks" },
    { title: "Mugs & Sippers", slug: "mugs-and-sippers" },
    { title: "Bags", slug: "bags" },
    { title: "Gift Sets", slug: "gift-sets" },
    { title: "Notebooks & Pens", slug: "notebooks-and-pens" },
    { title: "Electronics", slug: "electronics" },
    { title: "Mobile Stand & Keychains", slug: "mobile-stand-and-keychains"},
    { title: "Kitchen/Home Appliances", slug: "kitchen-home-appliances" },
    { title: "Eco-Friendly products", slug: "eco-friendly-products" },
];

export const allProducts = [
  // Bottles and Flasks
  { id: 1, productId: "GBI-4001", title: "Sports Bottle", description: "Durable and stylish sports bottle.", minimumOrder: 50, imageUrl: "/Product_Images/GBI-4001.webp", imageHint: "sports bottle", category: "Bottles and Flasks", subCategory: "Sports Bottles" },
  { id: 2, productId: "GBI-4006", title: "Sports Bottle", description: "Durable and stylish sports bottle.", minimumOrder: 50, imageUrl: "/Product_Images/GBI-4006.webp", imageHint: "sports bottle", category: "Bottles and Flasks", subCategory: "Sports Bottles" },
  { id: 3, productId: "GBI-4011", title: "Sports Bottle", description: "Durable and stylish sports bottle.", minimumOrder: 50, imageUrl: "/Product_Images/GBI-4011.webp", imageHint: "sports bottle", category: "Bottles and Flasks", subCategory: "Sports Bottles" },
  { id: 4, productId: "GBI-4071", title: "Glassware Bottle", description: "Elegant glassware bottle for any occasion.", minimumOrder: 30, imageUrl: "/Product_Images/GBI-4071.webp", imageHint: "glassware bottle", category: "Bottles and Flasks", subCategory: "Glassware Bottles" },
  { id: 5, productId: "GBI-4073", title: "Glassware Bottle", description: "Elegant glassware bottle for any occasion.", minimumOrder: 30, imageUrl: "/Product_Images/GBI-4073.webp", imageHint: "glassware bottle", category: "Bottles and Flasks", subCategory: "Glassware Bottles" },
  { id: 6, productId: "GBI-4083", title: "Glassware Bottle", description: "Elegant glassware bottle for any occasion.", minimumOrder: 30, imageUrl: "/Product_Images/GBI-4083.webp", imageHint: "glassware bottle", category: "Bottles and Flasks", subCategory: "Glassware Bottles" },
  { id: 7, productId: "GBI-4091", title: "Smart Reminder Bottle", description: "Stay hydrated with smart reminder bottles.", minimumOrder: 20, imageUrl: "/Product_Images/GBI-4091.webp", imageHint: "smart bottle", category: "Bottles and Flasks", subCategory: "Smart Reminder Bottles" },
  { id: 8, productId: "GBI-4093", title: "Smart Reminder Bottle", description: "Stay hydrated with smart reminder bottles.", minimumOrder: 20, imageUrl: "/Product_Images/GBI-4093.webp", imageHint: "smart bottle", category: "Bottles and Flasks", subCategory: "Smart Reminder Bottles" },
  { id: 9, productId: "GBI-4096", title: "Smart Reminder Bottle", description: "Stay hydrated with smart reminder bottles.", minimumOrder: 20, imageUrl: "/Product_Images/GBI-4096.webp", imageHint: "smart bottle", category: "Bottles and Flasks", subCategory: "Smart Reminder Bottles" },
  { id: 10, productId: "GBI-4085", title: "Bar Set HIP Flask", description: "Classic hip flask for your favorite spirits.", minimumOrder: 25, imageUrl: "/Product_Images/GBI-4085.webp", imageHint: "hip flask", category: "Bottles and Flasks", subCategory: "Bar Sets HIP Flasks" },
  { id: 11, productId: "GBI-4087", title: "Bar Set HIP Flask", description: "Classic hip flask for your favorite spirits.", minimumOrder: 25, imageUrl: "/Product_Images/GBI-4087.webp", imageHint: "hip flask", category: "Bottles and Flasks", subCategory: "Bar Sets HIP Flasks" },
  { id: 12, productId: "GBI-4089", title: "Bar Set HIP Flask", description: "Classic hip flask for your favorite spirits.", minimumOrder: 25, imageUrl: "/Product_Images/GBI-4089.webp", imageHint: "hip flask", category: "Bottles and Flasks", subCategory: "Bar Sets HIP Flasks" },

  // Mugs & Sippers
  { id: 13, productId: "4101", title: "Travel Mug", description: "Keep your drinks warm on the go.", minimumOrder: 40, imageUrl: "/Product_Images/4101.webp", imageHint: "travel mug", category: "Mugs & Sippers", subCategory: "Travel Mugs" },
  { id: 14, productId: "4103", title: "Travel Mug", description: "Keep your drinks warm on the go.", minimumOrder: 40, imageUrl: "/Product_Images/4103.webp", imageHint: "travel mug", category: "Mugs & Sippers", subCategory: "Travel Mugs" },
  { id: 15, productId: "4105", title: "Travel Mug", description: "Keep your drinks warm on the go.", minimumOrder: 40, imageUrl: "/Product_Images/4105.webp", imageHint: "travel mug", category: "Mugs & Sippers", subCategory: "Travel Mugs" },
  { id: 16, productId: "4110", title: "Double Wall Insulated Mug", description: "Insulated mugs to maintain temperature.", minimumOrder: 40, imageUrl: "/Product_Images/4110.webp", imageHint: "insulated mug", category: "Mugs & Sippers", subCategory: "Double wall insulated mugs" },
  { id: 17, productId: "4112", title: "Double Wall Insulated Mug", description: "Insulated mugs to maintain temperature.", minimumOrder: 40, imageUrl: "/Product_Images/4112.webp", imageHint: "insulated mug", category: "Mugs & Sippers", subCategory: "Double wall insulated mugs" },
  { id: 18, productId: "4117", title: "Double Wall Insulated Mug", description: "Insulated mugs to maintain temperature.", minimumOrder: 40, imageUrl: "/Product_Images/4117.webp", imageHint: "insulated mug", category: "Mugs & Sippers", subCategory: "Double wall insulated mugs" },
  { id: 19, productId: "112", title: "Sipper", description: "Convenient and easy-to-use sippers.", minimumOrder: 60, imageUrl: "/Product_Images/112.webp", imageHint: "sipper bottle", category: "Mugs & Sippers", subCategory: "Sippers" },
  { id: 20, productId: "114", title: "Sipper", description: "Convenient and easy-to-use sippers.", minimumOrder: 60, imageUrl: "/Product_Images/114.webp", imageHint: "sipper bottle", category: "Mugs & Sippers", subCategory: "Sippers" },
  { id: 21, productId: "116", title: "Sipper", description: "Convenient and easy-to-use sippers.", minimumOrder: 60, imageUrl: "/Product_Images/116.webp", imageHint: "sipper bottle", category: "Mugs & Sippers", subCategory: "Sippers" },

  // Bags
  { id: 22, productId: "4301", title: "Laptop Sleeve", description: "Protect your laptop with stylish sleeves.", minimumOrder: 35, imageUrl: "/Product_Images/4301.webp", imageHint: "laptop sleeve", category: "Bags", subCategory: "Laptop Sleeves" },
  { id: 23, productId: "4308", title: "Laptop Sleeve", description: "Protect your laptop with stylish sleeves.", minimumOrder: 35, imageUrl: "/Product_Images/4308.webp", imageHint: "laptop sleeve", category: "Bags", subCategory: "Laptop Sleeves" },
  { id: 24, productId: "4361", title: "Laptop Sleeve", description: "Protect your laptop with stylish sleeves.", minimumOrder: 35, imageUrl: "/Product_Images/4361.webp", imageHint: "laptop sleeve", category: "Bags", subCategory: "Laptop Sleeves" },
  { id: 25, productId: "4320", title: "Utility Bag", description: "Versatile bags for all your needs.", minimumOrder: 50, imageUrl: "/Product_Images/4320.webp", imageHint: "utility bag", category: "Bags", subCategory: "Utility bags" },
  { id: 26, productId: "4321", title: "Utility Bag", description: "Versatile bags for all your needs.", minimumOrder: 50, imageUrl: "/Product_Images/4321.webp", imageHint: "utility bag", category: "Bags", subCategory: "Utility bags" },
  { id: 27, productId: "4323", title: "Utility Bag", description: "Versatile bags for all your needs.", minimumOrder: 50, imageUrl: "/Product_Images/4323.webp", imageHint: "utility bag", category: "Bags", subCategory: "Utility bags" },
  { id: 28, productId: "4503", title: "Travel Bag", description: "Spacious and durable travel bags.", minimumOrder: 25, imageUrl: "/Product_Images/4503.webp", imageHint: "travel bag", category: "Bags", subCategory: "Travel bags" },
  { id: 29, productId: "4504", title: "Travel Bag", description: "Spacious and durable travel bags.", minimumOrder: 25, imageUrl: "/Product_Images/4504.webp", imageHint: "travel bag", category: "Bags", subCategory: "Travel bags" },
  { id: 30, productId: "4505", title: "Travel Bag", description: "Spacious and durable travel bags.", minimumOrder: 25, imageUrl: "/Product_Images/4505.webp", imageHint: "travel bag", category: "Bags", subCategory: "Travel bags" },
  { id: 31, productId: "4333", title: "Wallet", description: "Sleek and functional wallets.", minimumOrder: 70, imageUrl: "/Product_Images/4333.webp", imageHint: "wallet", category: "Bags", subCategory: "Wallets" },
  { id: 32, productId: "4336", title: "Wallet", description: "Sleek and functional wallets.", minimumOrder: 70, imageUrl: "/Product_Images/4336.webp", imageHint: "wallet", category: "Bags", subCategory: "Wallets" },
  { id: 33, productId: "4339", title: "Wallet", description: "Sleek and functional wallets.", minimumOrder: 70, imageUrl: "/Product_Images/4339.webp", imageHint: "wallet", category: "Bags", subCategory: "Wallets" },

  // Gift Sets
  { id: 34, productId: "4370", title: "Office Set", description: "Complete office gift sets for professionals.", minimumOrder: 20, imageUrl: "/Product_Images/4370.webp", imageHint: "office gift set", category: "Gift Sets", subCategory: "Office Sets" },
  { id: 35, productId: "4377", title: "Office Set", description: "Complete office gift sets for professionals.", minimumOrder: 20, imageUrl: "/Product_Images/4377.webp", imageHint: "office gift set", category: "Gift Sets", subCategory: "Office Sets" },
  { id: 36, productId: "4378", title: "Office Set", description: "Complete office gift sets for professionals.", minimumOrder: 20, imageUrl: "/Product_Images/4378.webp", imageHint: "office gift set", category: "Gift Sets", subCategory: "Office Sets" },
  { id: 37, productId: "4384", title: "Utility Gift Set", description: "Practical and useful utility gift sets.", minimumOrder: 30, imageUrl: "/Product_Images/4384.webp", imageHint: "utility gift set", category: "Gift Sets", subCategory: "Utility gift sets" },
  { id: 38, productId: "4388", title: "Utility Gift Set", description: "Practical and useful utility gift sets.", minimumOrder: 30, imageUrl: "/Product_Images/4388.webp", imageHint: "utility gift set", category: "Gift Sets", subCategory: "Utility gift sets" },
  { id: 39, productId: "4393", title: "Utility Gift Set", description: "Practical and useful utility gift sets.", minimumOrder: 30, imageUrl: "/Product_Images/4393.webp", imageHint: "utility gift set", category: "Gift Sets", subCategory: "Utility gift sets" },
  { id: 40, productId: "4398", title: "Induction Set", description: "Premium induction cookware sets.", minimumOrder: 15, imageUrl: "/Product_Images/4398.webp", imageHint: "induction set", category: "Gift Sets", subCategory: "Induction Sets" },
  { id: 41, productId: "4401", title: "Induction Set", description: "Premium induction cookware sets.", minimumOrder: 15, imageUrl: "/Product_Images/4401.webp", imageHint: "induction set", category: "Gift Sets", subCategory: "Induction Sets" },
  { id: 42, productId: "4403", title: "Induction Set", description: "Premium induction cookware sets.", minimumOrder: 15, imageUrl: "/Product_Images/4403.webp", imageHint: "induction set", category: "Gift Sets", subCategory: "Induction Sets" },

  // Notebooks & Pens
  { id: 43, productId: "4408", title: "Eco-friendly notebook", description: "Sustainable notebooks for the eco-conscious.", minimumOrder: 100, imageUrl: "/Product_Images/4408.webp", imageHint: "eco notebook", category: "Notebooks & Pens", subCategory: "Eco-friendly notebooks" },
  { id: 44, productId: "4410", title: "Eco-friendly notebook", description: "Sustainable notebooks for the eco-conscious.", minimumOrder: 100, imageUrl: "/Product_Images/4410.webp", imageHint: "eco notebook", category: "Notebooks & Pens", subCategory: "Eco-friendly notebooks" },
  { id: 45, productId: "4421", title: "Eco-friendly notebook", description: "Sustainable notebooks for the eco-conscious.", minimumOrder: 100, imageUrl: "/Product_Images/4421.webp", imageHint: "eco notebook", category: "Notebooks & Pens", subCategory: "Eco-friendly notebooks" },
  { id: 46, productId: "4431", title: "PU notebook", description: "Premium PU leather notebooks.", minimumOrder: 50, imageUrl: "/Product_Images/4431.webp", imageHint: "leather notebook", category: "Notebooks & Pens", subCategory: "PU notebooks" },
  { id: 47, productId: "4437", title: "PU notebook", description: "Premium PU leather notebooks.", minimumOrder: 50, imageUrl: "/Product_Images/4437.webp", imageHint: "leather notebook", category: "Notebooks & Pens", subCategory: "PU notebooks" },
  { id: 48, productId: "4440", title: "PU notebook", description: "Premium PU leather notebooks.", minimumOrder: 50, imageUrl: "/Product_Images/4440.webp", imageHint: "leather notebook", category: "Notebooks & Pens", subCategory: "PU notebooks" },
  { id: 49, productId: "4448", title: "Powerbank notebook", description: "Notebook with a built-in powerbank.", minimumOrder: 25, imageUrl: "/Product_Images/4448.webp", imageHint: "powerbank notebook", category: "Notebooks & Pens", subCategory: "Powerbank notebooks" },
  { id: 50, productId: "4449", title: "Powerbank notebook", description: "Notebook with a built-in powerbank.", minimumOrder: 25, imageUrl: "/Product_Images/4449.webp", imageHint: "powerbank notebook", category: "Notebooks & Pens", subCategory: "Powerbank notebooks" },
  { id: 51, productId: "4451", title: "Powerbank notebook", description: "Notebook with a built-in powerbank.", minimumOrder: 25, imageUrl: "/Product_Images/4451.webp", imageHint: "powerbank notebook", category: "Notebooks & Pens", subCategory: "Powerbank notebooks" },
  { id: 52, productId: "24", title: "Pen", description: "Elegant and smooth writing pens.", minimumOrder: 150, imageUrl: "/Product_Images/24.webp", imageHint: "luxury pen", category: "Notebooks & Pens", subCategory: "Pens" },
  { id: 53, productId: "25", title: "Pen", description: "Elegant and smooth writing pens.", minimumOrder: 150, imageUrl: "/Product_Images/25.webp", imageHint: "luxury pen", category: "Notebooks & Pens", subCategory: "Pens" },
  { id: 54, productId: "26", title: "Pen", description: "Elegant and smooth writing pens.", minimumOrder: 150, imageUrl: "/Product_Images/26.webp", imageHint: "luxury pen", category: "Notebooks & Pens", subCategory: "Pens" },
  
  // Electronics
  { id: 55, productId: "4454", title: "Charging Device", description: "A variety of charging devices.", minimumOrder: 40, imageUrl: "/Product_Images/4454.webp", imageHint: "charging device", category: "Electronics", subCategory: "Charging Devices" },
  { id: 56, productId: "1", title: "Charging Device", description: "A variety of charging devices.", minimumOrder: 40, imageUrl: "/Product_Images/1.webp", imageHint: "charging device", category: "Electronics", subCategory: "Charging Devices" },
  { id: 57, productId: "2", title: "Charging Device", description: "A variety of charging devices.", minimumOrder: 40, imageUrl: "/Product_Images/2.webp", imageHint: "charging device", category: "Electronics", subCategory: "Charging Devices" },
  { id: 58, productId: "3", title: "Cable connector & Power bank", description: "Stay connected and powered up.", minimumOrder: 30, imageUrl: "/Product_Images/3.webp", imageHint: "power bank cable", category: "Electronics", subCategory: "Cable connectors & Power banks" },
  { id: 59, productId: "4", title: "Cable connector & Power bank", description: "Stay connected and powered up.", minimumOrder: 30, imageUrl: "/Product_Images/4.webp", imageHint: "power bank cable", category: "Electronics", subCategory: "Cable connectors & Power banks" },
  { id: 60, productId: "5", title: "Cable connector & Power bank", description: "Stay connected and powered up.", minimumOrder: 30, imageUrl: "/Product_Images/5.webp", imageHint: "power bank cable", category: "Electronics", subCategory: "Cable connectors & Power banks" },
  { id: 61, productId: "6", title: "Cable connector & Power bank", description: "Stay connected and powered up.", minimumOrder: 30, imageUrl: "/Product_Images/6.webp", imageHint: "power bank cable", category: "Electronics", subCategory: "Cable connectors & Power banks" },
  { id: 62, productId: "7", title: "Cable connector & Power bank", description: "Stay connected and powered up.", minimumOrder: 30, imageUrl: "/Product_Images/7.webp", imageHint: "power bank cable", category: "Electronics", subCategory: "Cable connectors & Power banks" },
  { id: 63, productId: "8", title: "Cable connector & Power bank", description: "Stay connected and powered up.", minimumOrder: 30, imageUrl: "/Product_Images/8.webp", imageHint: "power bank cable", category: "Electronics", subCategory: "Cable connectors & Power banks" },
  { id: 64, productId: "9", title: "Humidifier", description: "Modern and quiet humidifiers.", minimumOrder: 20, imageUrl: "/Product_Images/9.webp", imageHint: "humidifier", category: "Electronics", subCategory: "Humidifiers" },
  { id: 65, productId: "10", title: "Humidifier", description: "Modern and quiet humidifiers.", minimumOrder: 20, imageUrl: "/Product_Images/10.webp", imageHint: "humidifier", category: "Electronics", subCategory: "Humidifiers" },
  { id: 66, productId: "11", title: "Humidifier", description: "Modern and quiet humidifiers.", minimumOrder: 20, imageUrl: "/Product_Images/11.webp", imageHint: "humidifier", category: "Electronics", subCategory: "Humidifiers" },
  { id: 67, productId: "12", title: "Lamp & clock", description: "Stylish lamps and clocks for your desk.", minimumOrder: 30, imageUrl: "/Product_Images/12.webp", imageHint: "desk lamp clock", category: "Electronics", subCategory: "Lamps & clocks" },
  { id: 68, productId: "13", title: "Lamp & clock", description: "Stylish lamps and clocks for your desk.", minimumOrder: 30, imageUrl: "/Product_Images/13.webp", imageHint: "desk lamp clock", category: "Electronics", subCategory: "Lamps & clocks" },
  { id: 69, productId: "14", title: "Lamp & clock", description: "Stylish lamps and clocks for your desk.", minimumOrder: 30, imageUrl: "/Product_Images/14.webp", imageHint: "desk lamp clock", category: "Electronics", subCategory: "Lamps & clocks" },
  { id: 70, productId: "15", title: "Lamp & clock", description: "Stylish lamps and clocks for your desk.", minimumOrder: 30, imageUrl: "/Product_Images/15.webp", imageHint: "desk lamp clock", category: "Electronics", subCategory: "Lamps & clocks" },
  { id: 71, productId: "16", title: "Lamp & clock", description: "Stylish lamps and clocks for your desk.", minimumOrder: 30, imageUrl: "/Product_Images/16.webp", imageHint: "desk lamp clock", category: "Electronics", subCategory: "Lamps & clocks" },
  { id: 72, productId: "17", title: "Lamp & clock", description: "Stylish lamps and clocks for your desk.", minimumOrder: 30, imageUrl: "/Product_Images/17.webp", imageHint: "desk lamp clock", category: "Electronics", subCategory: "Lamps & clocks" },
  { id: 73, productId: "33", title: "Pen drive", description: "High-speed and reliable pen drives.", minimumOrder: 100, imageUrl: "/Product_Images/33.webp", imageHint: "pen drive", category: "Electronics", subCategory: "Pen drives" },
  { id: 74, productId: "34", title: "Pen drive", description: "High-speed and reliable pen drives.", minimumOrder: 100, imageUrl: "/Product_Images/34.webp", imageHint: "pen drive", category: "Electronics", subCategory: "Pen drives" },
  { id: 75, productId: "35", title: "Pen drive", description: "High-speed and reliable pen drives.", minimumOrder: 100, imageUrl: "/Product_Images/35.webp", imageHint: "pen drive", category: "Electronics", subCategory: "Pen drives" },
  { id: 76, productId: "18", title: "Speaker", description: "Portable and powerful speakers.", minimumOrder: 25, imageUrl: "/Product_Images/18.webp", imageHint: "bluetooth speaker", category: "Electronics", subCategory: "Speakers" },
  { id: 77, productId: "36", title: "Speaker", description: "Portable and powerful speakers.", minimumOrder: 25, imageUrl: "/Product_Images/36.webp", imageHint: "bluetooth speaker", category: "Electronics", subCategory: "Speakers" },
  { id: 78, productId: "37", title: "Speaker", description: "Portable and powerful speakers.", minimumOrder: 25, imageUrl: "/Product_Images/37.webp", imageHint: "bluetooth speaker", category: "Electronics", subCategory: "Speakers" },

  // Mobile Stand & Keychains
  { id: 79, productId: "27", title: "Mobile Stand & Keychain", description: "Convenient stands and keychains for your mobile.", minimumOrder: 100, imageUrl: "/Product_Images/27.webp", imageHint: "mobile stand keychain", category: "Mobile Stand & Keychains", subCategory: "Mobile Stand & Keychains" },
  { id: 80, productId: "28", title: "Mobile Stand & Keychain", description: "Convenient stands and keychains for your mobile.", minimumOrder: 100, imageUrl: "/Product_Images/28.webp", imageHint: "mobile stand keychain", category: "Mobile Stand & Keychains", subCategory: "Mobile Stand & Keychains" },
  { id: 81, productId: "29", title: "Mobile Stand & Keychain", description: "Convenient stands and keychains for your mobile.", minimumOrder: 100, imageUrl: "/Product_Images/29.webp", imageHint: "mobile stand keychain", category: "Mobile Stand & Keychains", subCategory: "Mobile Stand & Keychains" },
  { id: 82, productId: "30", title: "Mobile Stand & Keychain", description: "Convenient stands and keychains for your mobile.", minimumOrder: 100, imageUrl: "/Product_Images/30.webp", imageHint: "mobile stand keychain", category: "Mobile Stand & Keychains", subCategory: "Mobile Stand & Keychains" },
  { id: 83, productId: "31", title: "Mobile Stand & Keychain", description: "Convenient stands and keychains for your mobile.", minimumOrder: 100, imageUrl: "/Product_Images/31.webp", imageHint: "mobile stand keychain", category: "Mobile Stand & Keychains", subCategory: "Mobile Stand & Keychains" },
  { id: 84, productId: "32", title: "Mobile Stand & Keychain", description: "Convenient stands and keychains for your mobile.", minimumOrder: 100, imageUrl: "/Product_Images/32.webp", imageHint: "mobile stand keychain", category: "Mobile Stand & Keychains", subCategory: "Mobile Stand & Keychains" },
  
  // Kitchen/Home Appliances
  { id: 85, productId: "4151", title: "Kitchen/Home Appliance", description: "High-quality appliances for your home.", minimumOrder: 15, imageUrl: "/Product_Images/4151.webp", imageHint: "kitchen appliance", category: "Kitchen/Home Appliances", subCategory: "Kitchen/Home Appliances" },
  { id: 86, productId: "4152", title: "Kitchen/Home Appliance", description: "High-quality appliances for your home.", minimumOrder: 15, imageUrl: "/Product_Images/4152.webp", imageHint: "kitchen appliance", category: "Kitchen/Home Appliances", subCategory: "Kitchen/Home Appliances" },
  { id: 87, productId: "4156", title: "Kitchen/Home Appliance", description: "High-quality appliances for your home.", minimumOrder: 15, imageUrl: "/Product_Images/4156.webp", imageHint: "kitchen appliance", category: "Kitchen/Home Appliances", subCategory: "Kitchen/Home Appliances" },
  { id: 88, productId: "21", title: "Kitchen/Home Appliance", description: "High-quality appliances for your home.", minimumOrder: 15, imageUrl: "/Product_Images/21.webp", imageHint: "kitchen appliance", category: "Kitchen/Home Appliances", subCategory: "Kitchen/Home Appliances" },
  { id: 89, productId: "22", title: "Kitchen/Home Appliance", description: "High-quality appliances for your home.", minimumOrder: 15, imageUrl: "/Product_Images/22.webp", imageHint: "kitchen appliance", category: "Kitchen/Home Appliances", subCategory: "Kitchen/Home Appliances" },
  { id: 90, productId: "23", title: "Kitchen/Home Appliance", description: "High-quality appliances for your home.", minimumOrder: 15, imageUrl: "/Product_Images/23.webp", imageHint: "kitchen appliance", category: "Kitchen/Home Appliances", subCategory: "Kitchen/Home Appliances" },
  
  // Eco-Friendly products (Assuming these are new and not in the sheet)
  { id: 91, productId: "PP-EF-001", title: "Bamboo Utensils", description: "Sustainable bamboo utensil sets.", minimumOrder: 80, imageUrl: "/Product_Images/PP-EF-001.webp", imageHint: "bamboo utensils", category: "Eco-Friendly products", subCategory: "Bamboo Utensils" },
  { id: 92, productId: "PP-EF-002", title: "Reusable Shopping Bags", description: "Durable and eco-friendly shopping bags.", minimumOrder: 120, imageUrl: "/Product_Images/PP-EF-002.webp", imageHint: "reusable bag", category: "Eco-Friendly products", subCategory: "Reusable Shopping Bags" },
];
